
spring:
  profiles:
    active: local
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/project1
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: epfzja1234@gmail.com
    password: zehpnoaaalfvvedy
    properties:
      mail:
        smtp:
          auto: true
          timeout: 5000
          starttls.enable: true



server:
  tomcat:
    max-http-form-post-size: 5MB
  servlet.session.timeout: 1800

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

